### ISSUE TITLE
Rownames error with ParseGEO

### ISSUE THREAD

**Issue by gszetosg** [showteeth/scfetch#1]
Hi,

Thanks for developing the package. Was looking to get data from Series GSE236082 and got this error running **ParseGEO**:

> Warning: Data is of class data.frame. Coercing to dgCMatrix.Error in validObject(.Object) : 
>   invalid class “LogMap” object: Rownames must be supplied

Any thoughts or fixes?

**Comment by showteeth** [comment]
Hi,

Currently, `scfetch` only supports the CellRanger output packaged in TAR file, such as [GSE200257](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE200257). In the initial development, we didn't consider the situation of the supplementary files in the form like [GSE236082](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE236082). 

We will update `scfetch` as soon as possible.

P.S:
I got a different error when downloading, can you show me the codes you used?
```R
GSE236082.seu <- ParseGEO(
  acce = "GSE236082", platform = NULL, supp.idx = 1, down.supp = TRUE, supp.type = "10x",
  out.folder = "/path/to/save"
)
```

>Error in ExtractGEOExpSupp10x(acce = acce, supp.idx = supp.idx, timeout = timeout, :
Does not support non-tar file for 10x mode!

YB

**Comment by showteeth** [comment]
Hi @gszetosg , 

Since you didn't reply, I solved this issue according to the error  on my machine:
>Error in ExtractGEOExpSupp10x(acce = acce, supp.idx = supp.idx, timeout = timeout, :
Does not support non-tar file for 10x mode!

**Step 1**: reinstall `scfetch` with `devtools::install_github("showteeth/scfetch")`
**Step 2**: use the following codes (I have tested):
```R
> GSE236082.seu <- ParseGEO(
  acce = "GSE236082", platform = NULL, down.supp = TRUE, supp.type = "10xSingle",
  out.folder = "/Users/soyabean/Desktop/tmp/scdown/issues"
)
> GSE236082.seu
An object of class Seurat 
78357 features across 19607 samples within 1 assay 
Active assay: RNA (78357 features, 0 variable features)
```

Let me know if you have any problems.

YB
